<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Hybrid-Framework" duration-ms="13800" started-at="2019-12-16T11:10:34Z" finished-at="2019-12-16T11:10:48Z">
    <groups>
    </groups>
    <test name="BankingApp Test" duration-ms="13800" started-at="2019-12-16T11:10:34Z" finished-at="2019-12-16T11:10:48Z">
      <class name="com.inetbanking.TestCases.TC_LoginTest_001">
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:com.inetbanking.TestCases.TC_LoginTest_001@7d9d1a19]" name="setUp" is-config="true" duration-ms="11183" started-at="2019-12-16T11:10:34Z" finished-at="2019-12-16T11:10:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="loginTest()[pri:0, instance:com.inetbanking.TestCases.TC_LoginTest_001@7d9d1a19]" name="loginTest" duration-ms="1952" started-at="2019-12-16T11:10:45Z" finished-at="2019-12-16T11:10:47Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.inetbanking.utilities.Reporting.onTestSuccess(Reporting.java:47)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:70)
at org.testng.internal.Invoker.runTestListeners(Invoker.java:1389)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:636)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="TearDown()[pri:0, instance:com.inetbanking.TestCases.TC_LoginTest_001@7d9d1a19]" name="TearDown" is-config="true" duration-ms="618" started-at="2019-12-16T11:10:47Z" finished-at="2019-12-16T11:10:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TearDown -->
      </class> <!-- com.inetbanking.TestCases.TC_LoginTest_001 -->
    </test> <!-- BankingApp Test -->
  </suite> <!-- Hybrid-Framework -->
</testng-results>
